/**
 * @file test_comparison.cpp
 * @brief Compare C++ CURE results with Python implementation
 * 
 * This test:
 * 1. Reads test data generated by Python
 * 2. Runs C++ CURE with same parameters
 * 3. Compares results using ARI and other metrics
 */

#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include <map>
#include <set>
#include <algorithm>
#include <filesystem>
#include <iomanip>

#include "cure/cure/cure.hpp"
#include "cure/cure/distance.hpp"

namespace fs = std::filesystem;
using namespace cure;

// ============================================================
// Utility Functions
// ============================================================

/**
 * @brief Read CSV file into matrix
 */
Matrix readCSV(const std::string& filename) {
    Matrix data;
    std::ifstream file(filename);
    
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open file " << filename << std::endl;
        return data;
    }
    
    std::string line;
    while (std::getline(file, line)) {
        if (line.empty()) continue;
        
        Point row;
        std::stringstream ss(line);
        std::string value;
        
        while (std::getline(ss, value, ',')) {
            row.push_back(std::stod(value));
        }
        
        if (!row.empty()) {
            data.push_back(row);
        }
    }
    
    return data;
}

/**
 * @brief Read labels from CSV file
 */
std::vector<int> readLabels(const std::string& filename) {
    std::vector<int> labels;
    std::ifstream file(filename);
    
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open file " << filename << std::endl;
        return labels;
    }
    
    std::string line;
    while (std::getline(file, line)) {
        if (line.empty()) continue;
        labels.push_back(std::stoi(line));
    }
    
    return labels;
}

/**
 * @brief Simple JSON parser for test parameters
 */
struct TestParams {
    int k = 3;
    int c = 5;
    double alpha = 0.3;
    double outlier_sample_fraction = 0.0;  // 0 = off, 0.5 = 1/2, 0.2 = 1/5 closest to centroid
    bool use_pearson = false;  // from params "metric": "pearson" or test name containing "pearson"
    bool scalable = false;    // from params "scalable": true -> use ScalableCURE
    
    static TestParams parse(const std::string& filename) {
        TestParams params;
        std::ifstream file(filename);
        
        if (!file.is_open()) {
            std::cerr << "Warning: Cannot open params file, using defaults" << std::endl;
            return params;
        }
        
        std::string content((std::istreambuf_iterator<char>(file)),
                            std::istreambuf_iterator<char>());
        
        // Simple parsing
        auto findValue = [&content](const std::string& key) -> std::string {
            size_t pos = content.find("\"" + key + "\"");
            if (pos == std::string::npos) return "";
            pos = content.find(":", pos);
            if (pos == std::string::npos) return "";
            pos++;
            while (pos < content.size() && (content[pos] == ' ' || content[pos] == '\t')) pos++;
            size_t end = content.find_first_of(",}\n", pos);
            std::string s = content.substr(pos, end - pos);
            if (s.size() >= 2 && s.front() == '"' && s.back() == '"')
                s = s.substr(1, s.size() - 2);
            return s;
        };
        
        std::string val;
        if (!(val = findValue("k")).empty()) params.k = std::stoi(val);
        if (!(val = findValue("c")).empty()) params.c = std::stoi(val);
        if (!(val = findValue("alpha")).empty()) params.alpha = std::stod(val);
        if (!(val = findValue("outlier_sample_fraction")).empty()) params.outlier_sample_fraction = std::stod(val);
        val = findValue("metric");
        if (val == "pearson") params.use_pearson = true;
        val = findValue("scalable");
        if (val == "true" || val == "1") params.scalable = true;
        
        return params;
    }
};

/**
 * @brief Compute Adjusted Rand Index
 * 
 * ARI = (RI - Expected_RI) / (max(RI) - Expected_RI)
 */
double computeARI(const std::vector<int>& labels1, const std::vector<int>& labels2) {
    if (labels1.size() != labels2.size() || labels1.empty()) {
        return 0.0;
    }
    
    size_t n = labels1.size();
    
    // Build contingency table
    std::map<std::pair<int,int>, int> contingency;
    std::map<int, int> sum_a, sum_b;
    
    for (size_t i = 0; i < n; ++i) {
        contingency[{labels1[i], labels2[i]}]++;
        sum_a[labels1[i]]++;
        sum_b[labels2[i]]++;
    }
    
    // Compute index
    auto comb2 = [](long long x) -> long long {
        return x * (x - 1) / 2;
    };
    
    long long sum_comb_nij = 0;
    for (const auto& [key, val] : contingency) {
        sum_comb_nij += comb2(val);
    }
    
    long long sum_comb_a = 0;
    for (const auto& [key, val] : sum_a) {
        sum_comb_a += comb2(val);
    }
    
    long long sum_comb_b = 0;
    for (const auto& [key, val] : sum_b) {
        sum_comb_b += comb2(val);
    }
    
    long long comb_n = comb2(n);
    
    if (comb_n == 0) return 1.0;
    
    double expected = (double)sum_comb_a * sum_comb_b / comb_n;
    double max_index = 0.5 * (sum_comb_a + sum_comb_b);
    
    if (max_index == expected) return 1.0;
    
    return (sum_comb_nij - expected) / (max_index - expected);
}

/**
 * @brief Compute cluster size distribution
 */
std::map<int, int> computeClusterSizes(const std::vector<int>& labels) {
    std::map<int, int> sizes;
    for (int label : labels) {
        sizes[label]++;
    }
    return sizes;
}

/**
 * @brief Get sorted cluster sizes
 */
std::vector<int> getSortedSizes(const std::map<int, int>& sizes) {
    std::vector<int> result;
    for (const auto& [k, v] : sizes) {
        result.push_back(v);
    }
    std::sort(result.begin(), result.end(), std::greater<int>());
    return result;
}

// ============================================================
// Test Runner
// ============================================================

struct TestResult {
    std::string name;
    double cpp_ari_vs_true;
    double python_ari_vs_true;
    double cpp_vs_python_ari;
    std::vector<int> cpp_sizes;
    std::vector<int> python_sizes;
    bool passed;
    std::string notes;
};

TestResult runTestCase(const std::string& test_dir, const std::string& name) {
    TestResult result;
    result.name = name;
    result.passed = true;
    
    std::cout << "  Running: " << name << std::endl;
    
    // Read data
    Matrix data = readCSV(test_dir + "/data.csv");
    std::vector<int> true_labels = readLabels(test_dir + "/true_labels.csv");
    TestParams params = TestParams::parse(test_dir + "/params.json");
    
    if (data.empty()) {
        result.passed = false;
        result.notes = "Failed to load data";
        return result;
    }
    
    std::cout << "    Data: " << data.size() << " points, " 
              << data[0].size() << " dimensions" << std::endl;
    std::cout << "    Params: k=" << params.k << ", c=" << params.c 
              << ", alpha=" << params.alpha
              << ", metric=" << (params.use_pearson ? "pearson" : "euclidean")
              << ", scalable=" << (params.scalable ? "true" : "false") << std::endl;
    
    // Use metric from params; fallback to name containing "pearson"
    bool use_pearson = params.use_pearson || (name.find("pearson") != std::string::npos);
    
    std::vector<int> cpp_labels;
    if (params.scalable) {
        ScalableCureConfig config;
        config.k = params.k;
        config.c = params.c;
        config.alpha = params.alpha;
        ScalableCURE cure(config);
        if (use_pearson) cure.setMetric(DistanceMetric::Pearson);
        cpp_labels = cure.fit_predict(data);
    } else {
        CureConfig config;
        config.k = params.k;
        config.c = params.c;
        config.alpha = params.alpha;
        config.outlier_sample_fraction = params.outlier_sample_fraction;
        CURE cure(config);
        if (use_pearson) cure.setMetric(DistanceMetric::Pearson);
        cpp_labels = cure.fit_predict(data);
    }
    
    // Compute metrics
    result.cpp_ari_vs_true = computeARI(cpp_labels, true_labels);
    
    auto cpp_sizes_map = computeClusterSizes(cpp_labels);
    result.cpp_sizes = getSortedSizes(cpp_sizes_map);
    
    std::cout << "    C++ ARI vs true: " << std::fixed << std::setprecision(4) 
              << result.cpp_ari_vs_true << std::endl;
    std::cout << "    C++ cluster sizes: ";
    for (int s : result.cpp_sizes) std::cout << s << " ";
    std::cout << std::endl;
    
    // Write C++ results to file for plotting (Python can load and compare visually)
    {
        std::ofstream cpp_out(test_dir + "/cpp_results.json");
        if (cpp_out.is_open()) {
            cpp_out << "{\n  \"labels\": [";
            for (size_t i = 0; i < cpp_labels.size(); ++i) {
                if (i > 0) cpp_out << ", ";
                cpp_out << cpp_labels[i];
            }
            cpp_out << "],\n  \"ari_vs_true\": " << std::fixed << std::setprecision(6)
                    << result.cpp_ari_vs_true << ",\n  \"n_clusters\": " << result.cpp_sizes.size()
                    << ",\n  \"cluster_sizes\": [";
            for (size_t i = 0; i < result.cpp_sizes.size(); ++i) {
                if (i > 0) cpp_out << ", ";
                cpp_out << result.cpp_sizes[i];
            }
            cpp_out << "]\n}\n";
        }
    }
    
    // Try to read Python results for comparison (supports "result" or "euclidean"/"pearson" keys)
    std::ifstream python_file(test_dir + "/python_results.json");
    if (python_file.is_open()) {
        std::string content((std::istreambuf_iterator<char>(python_file)),
                            std::istreambuf_iterator<char>());
        size_t pos = std::string::npos;
        if (content.find("\"result\"") != std::string::npos)
            pos = content.find("\"result\"");
        if (pos == std::string::npos) {
            std::string search_key = use_pearson ? "pearson" : "euclidean";
            pos = content.find("\"" + search_key + "\"");
        }
        if (pos != std::string::npos) {
            size_t ari_pos = content.find("\"ari_vs_true\"", pos);
            if (ari_pos != std::string::npos) {
                size_t colon_pos = content.find(":", ari_pos);
                if (colon_pos != std::string::npos) {
                    size_t end_pos = content.find_first_of(",}", colon_pos);
                    std::string ari_str = content.substr(colon_pos + 1, end_pos - colon_pos - 1);
                    // Trim whitespace
                    ari_str.erase(0, ari_str.find_first_not_of(" \t\n"));
                    ari_str.erase(ari_str.find_last_not_of(" \t\n") + 1);
                    result.python_ari_vs_true = std::stod(ari_str);
                    
                    std::cout << "    Python ARI vs true: " << std::fixed << std::setprecision(4) 
                              << result.python_ari_vs_true << std::endl;
                }
            }
            
            // Parse Python labels for direct comparison
            size_t labels_pos = content.find("\"labels\"", pos);
            if (labels_pos != std::string::npos) {
                size_t arr_start = content.find("[", labels_pos);
                size_t arr_end = content.find("]", arr_start);
                if (arr_start != std::string::npos && arr_end != std::string::npos) {
                    std::string labels_str = content.substr(arr_start + 1, arr_end - arr_start - 1);
                    std::vector<int> python_labels;
                    std::stringstream ss(labels_str);
                    std::string item;
                    while (std::getline(ss, item, ',')) {
                        item.erase(0, item.find_first_not_of(" \t\n"));
                        item.erase(item.find_last_not_of(" \t\n") + 1);
                        if (!item.empty()) {
                            python_labels.push_back(std::stoi(item));
                        }
                    }
                    
                    if (python_labels.size() == cpp_labels.size()) {
                        result.cpp_vs_python_ari = computeARI(cpp_labels, python_labels);
                        std::cout << "    C++ vs Python ARI: " << std::fixed << std::setprecision(4) 
                                  << result.cpp_vs_python_ari << std::endl;
                        
                        auto python_sizes_map = computeClusterSizes(python_labels);
                        result.python_sizes = getSortedSizes(python_sizes_map);
                        
                        std::cout << "    Python cluster sizes: ";
                        for (int s : result.python_sizes) std::cout << s << " ";
                        std::cout << std::endl;
                    }
                }
            }
        }
    }
    
    // Validation
    double ari_threshold = 0.7;  // Minimum acceptable ARI
    double ari_diff_threshold = 0.2;  // Maximum acceptable difference from Python
    
    if (result.cpp_ari_vs_true < ari_threshold) {
        result.notes += "Low ARI vs true labels. ";
    }
    
    if (result.cpp_vs_python_ari > 0 && result.cpp_vs_python_ari < 0.8) {
        result.notes += "Significant difference from Python. ";
    }
    
    if (std::abs(result.cpp_ari_vs_true - result.python_ari_vs_true) > ari_diff_threshold) {
        result.notes += "ARI differs significantly from Python. ";
    }
    
    // Check cluster sizes match approximately
    if (!result.python_sizes.empty() && result.cpp_sizes.size() == result.python_sizes.size()) {
        int total_diff = 0;
        for (size_t i = 0; i < result.cpp_sizes.size(); ++i) {
            total_diff += std::abs(result.cpp_sizes[i] - result.python_sizes[i]);
        }
        if (total_diff > static_cast<int>(data.size()) * 0.2) {
            result.notes += "Cluster sizes differ significantly. ";
        }
    }
    
    if (result.notes.empty()) {
        result.notes = "OK";
    }
    
    return result;
}

int main(int argc, char* argv[]) {
    std::cout << "CURE Algorithm Comparison Tests: C++ vs Python\n";
    std::cout << std::string(70, '=') << "\n\n";
    
    // Find test data directory
    std::string test_data_dir;
    
    // Try relative paths
    std::vector<std::string> possible_paths = {
        "tests/comparison/test_data",
        "../tests/comparison/test_data",
        "../../tests/comparison/test_data",
        "./test_data"
    };
    
    if (argc > 1) {
        possible_paths.insert(possible_paths.begin(), argv[1]);
    }
    
    for (const auto& path : possible_paths) {
        if (fs::exists(path) && fs::is_directory(path)) {
            test_data_dir = path;
            break;
        }
    }
    
    if (test_data_dir.empty()) {
        std::cout << "test_comparison: Skipped (no test data).\n";
        std::cout << "To run Python vs C++ comparison: python3 tests/comparison/generate_test_data.py\n";
        return 0;  // Pass so CTest succeeds; comparison is optional
    }
    
    std::cout << "Test data directory: " << test_data_dir << "\n\n";
    
    // Find all test cases
    std::vector<std::string> test_cases;
    for (const auto& entry : fs::directory_iterator(test_data_dir)) {
        if (entry.is_directory()) {
            test_cases.push_back(entry.path().filename().string());
        }
    }
    std::sort(test_cases.begin(), test_cases.end());
    
    if (test_cases.empty()) {
        std::cout << "test_comparison: Skipped (no test cases in directory).\n";
        std::cout << "To run: python3 tests/comparison/generate_test_data.py\n";
        return 0;  // Pass so CTest succeeds
    }
    
    std::cout << "Found " << test_cases.size() << " test cases\n\n";
    
    // Run all tests
    std::vector<TestResult> results;
    
    for (const auto& test_name : test_cases) {
        std::string test_path = test_data_dir + "/" + test_name;
        TestResult result = runTestCase(test_path, test_name);
        results.push_back(result);
        std::cout << "    Status: " << result.notes << "\n\n";
    }
    
    // Summary
    std::cout << std::string(70, '=') << "\n";
    std::cout << "SUMMARY\n";
    std::cout << std::string(70, '-') << "\n";
    
    std::cout << std::left << std::setw(25) << "Test Case" 
              << std::setw(12) << "C++ ARI"
              << std::setw(12) << "Py ARI"
              << std::setw(12) << "C++vsPy"
              << "Status\n";
    std::cout << std::string(70, '-') << "\n";
    
    int passed = 0;
    for (const auto& r : results) {
        std::cout << std::left << std::setw(25) << r.name.substr(0, 24)
                  << std::fixed << std::setprecision(4)
                  << std::setw(12) << r.cpp_ari_vs_true
                  << std::setw(12) << r.python_ari_vs_true
                  << std::setw(12) << r.cpp_vs_python_ari
                  << (r.notes == "OK" ? "PASS" : "CHECK") << "\n";
        if (r.notes == "OK") passed++;
    }
    
    std::cout << std::string(70, '-') << "\n";
    std::cout << "Passed: " << passed << "/" << results.size() << "\n";
    
    // Detailed analysis
    std::cout << "\n" << std::string(70, '=') << "\n";
    std::cout << "ANALYSIS\n";
    std::cout << std::string(70, '-') << "\n";
    
    double total_cpp_ari = 0, total_py_ari = 0, total_diff = 0;
    int count = 0;
    
    for (const auto& r : results) {
        if (r.python_ari_vs_true > 0) {
            total_cpp_ari += r.cpp_ari_vs_true;
            total_py_ari += r.python_ari_vs_true;
            total_diff += std::abs(r.cpp_ari_vs_true - r.python_ari_vs_true);
            count++;
        }
    }
    
    if (count > 0) {
        std::cout << "Average C++ ARI:    " << std::fixed << std::setprecision(4) 
                  << (total_cpp_ari / count) << "\n";
        std::cout << "Average Python ARI: " << std::fixed << std::setprecision(4) 
                  << (total_py_ari / count) << "\n";
        std::cout << "Average ARI diff:   " << std::fixed << std::setprecision(4) 
                  << (total_diff / count) << "\n";
        
        if (total_cpp_ari / count >= total_py_ari / count - 0.05) {
            std::cout << "\nConclusion: C++ implementation performs comparably to Python.\n";
        } else {
            std::cout << "\nWarning: C++ implementation may need review.\n";
        }
    }
    
    return (passed == static_cast<int>(results.size())) ? 0 : 1;
}
